ERROR_CODE = [
    "SRC_EMPTY",
    "TGT_EMPTY",
    "SRC_AND_TGT_IDENTICAL",
    "SRC_IN_TGT",
    "TGT_IN_SRC",
    "SRC_REPEATED",
    "TGT_REPEATED",
    "BRACKET_MISMATCH",
    "INVALID_LANG_IN_SRC",
    "INVALID_LANG_IN_TGT",
    "INVALID_SRC_LANG",
    "INVALID_TGT_LANG",
    "INVALID_SRC_AND_TGT_LANG",
    "SRC_TOO_LONG",
    "TGT_TOO_LONG",
    "SRC_TOO_SHORT",
    "TGT_TOO_SHORT",
    "SRC_TOO_LONGER",
    "TGT_TOO_LONGER",
    "LONG_WORD_IN_SRC",
    "LONG_WORD_IN_TGT",
    "NUMBER_MISMATCH",
]

MAX_SENT_LEN = 100
MIN_SENT_LEN = 1
MAX_WORD_LEN = 20
SENT_LEN_RATIO = 5
